services:

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ignition:/usr/share/nginx/html/ignition
      - ./nginx/cloud-init:/usr/share/nginx/html/cloud-init
    network_mode: host
    cap_add:
      - NET_ADMIN

  tftp:
    container_name: tftp
    build: ./tftp
    network_mode: host
    cap_add:
      - NET_ADMIN

  dhcpd:
    container_name: dhcpd
    image: sirferdek/isc-dhcp-server
    network_mode: host
    volumes:
      - ./dhcpd/dhcpd.conf:/etc/dhcp/dhcpd.conf
    cap_add:
      - NET_ADMIN
